# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0da9b137f834168c4084ecd2810956ab3465d76efb08b8616c7843147ba6237d7c2781e1490d3aa2ffaab6387c3c723242da0132f830ba53f33236d72453127e

test:
  secret_key_base: ba721fc78c441a329bc2e94186665c933f062a7933f9ebcb22196508f60064d074139966364216753c32fb6f91c0bc35757e09773a0c8781f4c2ec8ea2f7a38c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
